# 4 Custom Linear regression using Inheritance

In [21]:
# import the required module from scikit learn
import numpy as np
from sklearn import metrics
from sklearn.base import BaseEstimator
from sklearn.base import RegressorMixin
from sklearn.linear_model import LinearRegression
from sklearn.utils.estimator_checks import check_estimator
from sklearn.utils.estimator_checks import check_estimators_nan_inf
from sklearn.utils.estimator_checks import parametrize_with_checks
from sklearn.utils.validation import check_is_fitted,check_X_y,check_array
from sklearn.model_selection import train_test_split
from numpy import isnan, isinf, float64
from sklearn.metrics import r2_score


1. Create a python class called MyLinearRegression
2. Ensure your class inherit from sklearn BaseEstimator and RegressorMixin
3. Implement fit(X,Y) method, and returns self
4. Implement predict(X) method

In [22]:
class MyLinearregression(BaseEstimator, RegressorMixin):
    
    def find_covariance(self, x, mean_x, y, mean_y):
        covariance = 0.0
        for i in range(len(x)):
            covariance += (x[i] - mean_x) * (y[i] - mean_y)
        return covariance
    
    def variance(self, x, mean_x):
        var = 0.0
        for i in range(len(x)):
            var += (x[i] - mean_x) * (x[i] - mean_x)
        return var

    def find_B0_B1(self, X, Y):
        beta1= 0
        beta0 = 0
        x = X
        y = Y
        x_mean = np.mean(x)
        y_mean = np.mean(y)
        beta1 = self.find_covariance(x, x_mean, y, y_mean) / self.variance(x,x_mean)
        beta0 = y_mean - beta1 * x_mean
        return beta1, beta0
    
    def fit(self, X,y):
        self.coeff_ , self.intercept_ = self.find_B0_B1(X,y)

    def predict(self, X):
        predicted = self.intercept_ + self.coeff_ * X
        return predicted


6. Fit the dataset below using your custom estimator. Remember 80:20 split

In [23]:
X = np.arange(0,5.5,0.5)
# X
y = np.array([6,4.83,3.7,3.15,2.14,1.83,1.49,1.21,0.96,0.73,0.64])
y

array([6.  , 4.83, 3.7 , 3.15, 2.14, 1.83, 1.49, 1.21, 0.96, 0.73, 0.64])

In [24]:
X = X.reshape(-1,1)
y = y.reshape(-1,1)
x_train , x_valid, y_train, y_valid = train_test_split(X, y , test_size=0.2)
print(" X_Train Shape : ",x_train.shape,"\nX_Valid Shape : ",x_valid.shape,"\nY_Train Shape : ",y_train.shape,"\nY_valid Shape : ",y_valid.shape)

 X_Train Shape :  (8, 1) 
X_Valid Shape :  (3, 1) 
Y_Train Shape :  (8, 1) 
Y_valid Shape :  (3, 1)


In [25]:
print("\nX_train :\n",x_train)
print("\nY_train :\n",y_train)
print("\nX_Test :\n",x_valid)
print("\nY_test :\n",y_valid)


X_train :
 [[0. ]
 [5. ]
 [1.5]
 [4.5]
 [3.5]
 [2.5]
 [1. ]
 [2. ]]

Y_train :
 [[6.  ]
 [0.64]
 [3.15]
 [0.73]
 [1.21]
 [1.83]
 [3.7 ]
 [2.14]]

X_Test :
 [[4. ]
 [3. ]
 [0.5]]

Y_test :
 [[0.96]
 [1.49]
 [4.83]]


In [26]:
print("\nX_train shape :\n",x_train.shape)
print("\nY_train shape  :\n",y_train.shape)
print("\nX_Test shape  :\n",x_valid.shape)
print("\nY_test shape  :\n",y_valid.shape)


X_train shape :
 (8, 1)

Y_train shape  :
 (8, 1)

X_Test shape  :
 (3, 1)

Y_test shape  :
 (3, 1)


In [27]:
model = MyLinearregression()
model.fit(x_train, y_train)
y_pred = model.predict(x_valid)
R_score = r2_score(y_valid, y_pred)

In [28]:
print("The predicted Y_values after fitting the simple linear regression model is: \n")
y_pred

The predicted Y_values after fitting the simple linear regression model is: 



array([[0.96071429],
       [1.93690476],
       [4.37738095]])

In [29]:
print(" The predicted R_2 Score is:\t ",R_score)

 The predicted R_2 Score is:	  0.9540473723165355


5. Use check estimator() method to know if your estimator(MyLinearRegression) is valid

In [30]:
check_estimator(MyLinearregression(),generate_only = True)

<generator object check_estimator.<locals>.checks_generator at 0x11ff0a430>